### PR TITLE
Added more suspicious links

### PR DESCRIPTION
**Pull request by sahilasopa**
added more phishing links in spamLinks.txt

### CODE REVIEW

**Comment by MoonTM-GIT** [comment]
Where did you find these?

**Comment by sahilasopa** [comment]
> Where did you find these?

https://github.com/DevSpen/scam-links/blob/master/src/links.txt

**Comment by danthe1st** [comment]
The bot could fetch the list of links on startup (and caching them if fetching doesn't work) instead of relying on PRs whenever the list is changed.

**Comment by sahilasopa** [comment]
> The bot could fetch the list of links on startup (and caching them if fetching doesn't work) instead of relying on PRs whenever the list is changed.

Yup, I was thinking the same

**Pull request merged**
