### PR TITLE
Improved /help account Formatting

### PR DESCRIPTION
**Pull request by andrewlalis**
We've gotten several complaints about this:
https://discord.com/channels/648956210850299986/752535909228085348/984352629884862496

So I have improved the UI to:
- Show the current level first.
- Then show the progress to the next level
- Removed decimals from the XP since it takes up space and nobody needs it to be that precise.

### CODE REVIEW

**Review by MoonTM-GIT — APPROVED** [review]

**Comment by DynxstyGIT** [comment]
looks good!
we thought of changing the progress bar itself too though, as it’s on 2 separate lines and looks ugly on iOS 

image

Any ideas on that?

**Comment by andrewlalis** [comment]
@DynxstyGIT you can use block elements: https://en.wikipedia.org/wiki/Block_Elements

This might be a bit trickier, but it can be used to maybe make something that looks a little nicer.

**Comment by MoonTM-GIT** [comment]
I think we ready had some pretty good ideas in the staff chat, I can't find it right now but I know they were from Liquid

**Comment by liquiddevelopmentnet** [comment]
image
We had this one here.

**Comment by liquiddevelopmentnet** [comment]
Also, I would suggest to include the total help XP in `/help account`
ref: https://canary.discord.com/channels/648956210850299986/752535909228085348/985221082791419934

**Comment by andrewlalis** [comment]
I think I'll just keep the current progress bar for this pull request, and make a separate pull request for an updated progress bar, that way I can add tests without cluttering things up. But I did add a total XP thing so this should be ready to go.

**Review by DynxstyGIT — APPROVED** [review]

**Pull request merged**
