### PR TITLE
replace f*cks with hugs

### PR DESCRIPTION
**Pull request by danthe1st**
https://lkml.org/lkml/2018/12/1/105

### CODE REVIEW

**Review by DynxstyGIT — APPROVED** [review]

**Comment by danthe1st** [comment]
Note that the username/avatar cannot be set as JDA5 currently doesn't have webhook support.

**Comment by DynxstyGIT** [comment]
you might want to take a look at this: https://github.com/MinnDevelopment/discord-webhooks

**Review by DynxstyGIT — APPROVED** [review]

**Comment by DynxstyGIT** [comment]
It would be great if you (or someone else) could test this functionality tho

**Comment by danthe1st** [comment]
I tested it with normal text, images, images devlared as spoilers and in a thread. However, i still think someone else should test it in isolation.

Note that obtaining non-image attachments currently fail due to a bug (fixed but the fix is not yet published) in JDA.

**Comment by MoonTM-GIT** [comment]
I'll test it a bit

**Comment by MoonTM-GIT** [comment]
Okay, so something that is kind of expected but I would still like to mention, is that voice-text channels are not supported by JDA yet (https://github.com/DV8FromTheWorld/JDA/pull/2072), so it doesn't work in these obviously

Other than that I haven't found anything that didn't work as expected, except for non-image attachments which you already mentioned

**Review by MoonTM-GIT — APPROVED** [review]
Not tested

**Comment by MoonTM-GIT** [comment]
Not sure if we still want someone else to test this though

**Comment by DynxstyGIT** [comment]
would be cool if you cloud extract this webhook stuff into a separate method/class tho

**Comment by DynxstyGIT** [comment]
(for things like the messagelink listener)

**Comment by MoonTM-GIT** [comment]
Oh, something I just noticed, if I ping someone in my initial message the ping will (as it shouldn't) not go through to the message the bot sends. This might lead to confusion as someone might be looking for the message he was pinged in, which he can't find that easily since it doesn't have that orange mark, so we might want to disable this functionality for messages that include any pings

**Comment by danthe1st** [comment]
Yes but if that feature would accept pings, it should be capped to e.g. a maximum of three mentions per message.
Aside from that, I might need to explicitely exclude the suggestion channel.

**Comment by MoonTM-GIT** [comment]
I wasn't suggesting to let pings through, that would lead to more confusion as people would he shown two pings, instead it could just not replace anything in messages that include pings to cause no confusion about pings

**Comment by danthe1st** [comment]
> would be cool if you cloud extract this webhook stuff into a separate method/class tho

Done

> I wasn't suggesting to let pings through, that would lead to more confusion as people would he shown two pings, instead it could just not replace anything in messages that include pings to cause no confusion about pings

Done

**Review by DynxstyGIT — APPROVED** [review]

**Comment by danthe1st** [comment]
The functionality is implemented and has been tested.

**Comment by MoonTM-GIT** [comment]
yay

**Comment by DynxstyGIT** [comment]
this is a huge step for the java community

**Pull request merged**
