### PR TITLE
use damerau-levenshtein distance instead of direct comparison

### PR DESCRIPTION
**Pull request by gsayson**
In the original implementation of `HugListener`, a simple equality check was used. This resulted in plenty of easy bypasses such as "fug" and "fck".

This PR improves the detection mechanism such that instead of an *equality* check being used, a *similarity* check is used to identify some bypasses through the Damerau-Levenshtein algorithm. 

Given a string, the algorithm measures the number of transpositions, substitutions, insertions, or deletions, of a character in order to match the string `"fuck"`.

### CODE REVIEW

**Comment by DynxstyGIT** [comment]
Hey, this is actually pretty cool, but I don't know if we really want something like this as we actually don't want to censor "fuck" by itself. The current implementation is more like a joke, which one can bypass easily

If we decide to do this, this behaviour should be controllable using the /preferences command imo

**Comment by danthe1st** [comment]
Note that for _censoring_, reading/reacting to automod logs would be more effective (if we ever plan to do that).

**Comment by DynxstyGIT** [comment]
Yeah, but we don't want to censor stuff. And we never will

**Comment by DynxstyGIT** [comment]
The only thing we ever did was "Glyph", "Deveden" and "Coda", but that was just for fun to annoy big rat :^)

**Comment by liquiddevelopmentnet** [comment]
Pull request of the year

**Comment by DynxstyGIT** [comment]
Closed due to inactivity

**Pull request closed without merging**
